committer:
  email: "netcms@email.com"
  name: "netcms"

assets_dir: "data/assets"

content_dir: "data/content"

content_types:
  - name: post
    format: yml
    title_field: title
    fields:
      - name: title
        type: text
        label: Title
        params: {}

      - name: body
        type: rich
        label: Post body
        params: {}
